# Generated by Django 4.2.5 on 2023-09-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='leagues/')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_under_goals_type', models.CharField(max_length=10)),
                ('over_under_goals_value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('over_under_goals_confidence', models.IntegerField()),
                ('more_corners_type', models.CharField(max_length=10)),
                ('more_corners_value', models.CharField(max_length=100)),
                ('more_corners_confidence', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet_app.match')),
            ],
        ),
    ]
